#!/bin/bash

echo "Running lint check..."

./gradlew spotlessCheck --init-script scripts/init.gradle.kts --no-configuration-cache --stacktrace

status=$?

# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1
exit 0
