name: Test Report
on: [push]
jobs:
  Build:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare Env
        run: |
          mkdir keystore
          cd . > keystore/keystore.properties
          cd . > keystore/defi_wallet.jks
          echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 --decode > keystore/keystore.properties
          echo ${{ secrets.KEYSTORE_FILE }} | base64 --decode > keystore/defi_wallet.jks

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        run: ./gradlew app:jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: "app/build/reports/coverage/androidTest/debug/report.xml"