name: Test Report
on: [push]
env:
  JAVA_OPTS: "-Xmx4096m"
  GRADLE_OPTS: -Xmx4096m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
jobs:
  Build:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare Env
        run: |
          mkdir keystore
          cd . > keystore/keystore.properties
          cd . > keystore/github_token.properties
          cd . > keystore/defi_wallet.jks
          echo ${{ secrets.TOKEN_INFO }} | base64 --decode > keystore/github_token.properties
          echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 --decode > keystore/keystore.properties
          echo ${{ secrets.KEYSTORE_FILE }} | base64 --decode > keystore/defi_wallet.jks

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate cache key
        run: ./scripts/checksum.sh . checksum.txt

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Unit Test with Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.14.3
        with:
          api-level: 33
          script: ./gradlew app:jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: "app/build/reports/coverage/androidTest/debug/report.xml"