name: Unit Test Checking
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  JAVA_OPTS: "-Xmx4096m"
  GRADLE_OPTS: -Xmx4096m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

jobs:
  Prepare:
    uses: BreakZero/CryptoDeFiWallet-Mobile/.github/workflows/pre-workflow.yml@main

  RunTest:
    runs-on: macos-12
    needs: Prepare

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          - name: Load Files
            run: |
              mkdir keystore
              cd . > keystore/keystore.properties
              cd . > keystore/github_token.properties
              cd . > keystore/defi_wallet.jks
              echo ${{ secrets.TOKEN_INFO }} | base64 --decode > keystore/github_token.properties
              echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 --decode > keystore/keystore.properties
              echo ${{ secrets.KEYSTORE_FILE }} | base64 --decode > keystore/defi_wallet.jks

          - name: Setup Java
            uses: actions/setup-java@v3
            with:
              distribution: 'temurin'
              java-version: '11'

          - name: Generate cache key
            run: ./scripts/checksum.sh . checksum.txt

          - name: Gradle cache
            uses: actions/cache@v3
            with:
              path: |
                ~/.gradle/caches/modules-*
                ~/.gradle/caches/jars-*
                ~/.gradle/caches/build-cache-*
              key: gradle-${{ hashFiles('checksum.txt') }}

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run test task
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew wallet:jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: "wallet/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"